### ISSUE TITLE
Dashboards (Technical Writer, Moderator, Admin)

### ISSUE THREAD

**Issue by jamnjeri** [jamnjeri/Moringa-School-Daily#10]
## Description

A page that changes according to the role of the user. (roles: technical writer, moderator, admin)

## Scenarios

- A technical writer can view the articles page/feed, categories page and notifications page
- A moderator and admin can view all other pages (users page)

## Tasks

- [ ] Articles Page
   - [ ] Displays 3 main buttons: Published, Approved, Rejected 
   - [ ] Each card when pressed display's a user's articles that fit said category
- [ ] Categories Page 
  - [ ] Displays a list of the available categories and specifies which one a user has subscribed to.
  - [ ] The moderator and admin have an additional button that allows them to create a new category
- [ ] Users Page (Only available for moderators and admins)
  - [ ] Displays a list of all users of the app in a summary table
  - [ ] Search bar to be able to search for a specific user
  - [ ] An admin is the only one with the option to delete a user 
- [ ] Notifications Page
  - [ ] Displays a list of all notifications specific to that user
