### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jamnjeri** [jamnjeri/Moringa-School-Daily#2]
## Description

Create an appropriate footer that will be used throughout the site 

## Scenarios

- A user should be able to access the site's social media handles through the footer.
- A user should be able to 

## Tasks

- [x] Contains copyright notice
- [x] Contains social media icons
- [x] Contains website logo
- [x] Contains contact information
