### ISSUE TITLE
Home Page/ Landing Page

### ISSUE THREAD

**Issue by jamnjeri** [jamnjeri/Moringa-School-Daily#4]
## Description

This is the page that all users get navigated to when they load the site.

## Scenarios

- A user needs to be able to see cards of a few articles.
- A user needs to be be able to read any article or browse through the articles.

## Tasks

- [ ] A random article at the top (Larger card (width))
- [ ] Editor's Pick section
- [ ] Category buttons to filter articles by specific categories
- [ ] Several smaller cards of different cards serving as article previews

**Comment by fatouuuu** [comment]
made changes to the landing page design.
