### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by jamnjeri** [jamnjeri/Moringa-School-Daily#8]
## Description

A user's profile page that displays the logged in user's details

## Scenarios

- A user needs to be able to see their details
- A user needs to be able to update their details

## Tasks

- [ ] Profile Picture Icon
- [ ] Update Profile button that activates update form.
- [ ] Profile Form with pre-filled entries:
  - [ ] Username
  - [ ] Full name
  - [ ] Email
  - [ ] Password
- [ ] Submit button
